server:
   port: 8081
spring:
   application:
      name: emart-buyer
   profiles:
      active: test
   zipkin:
      baseUrl: http://localhost:8080
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://127.0.0.1:3306/stockmarket?useUnicode=true&characterEncoding=utf-8
      #url: jdbc:mysql://127.0.0.1:3306/stockmarket?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      url: jdbc:mysql://127.0.0.1:3306/emart?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: 1qazZAQ!
   jpa:
    properties:
      hibernate:
#         database-platform: org.hibernate.dialect.MySQLDialect
#ddl-auto: create
         dialect: org.hibernate.dialect.MySQL5Dialect
         ddl-auto: create
         show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
eureka:  client:    serviceUrl:
     defaultZone: http://localhost:7001/eureka